/*!CK:3304236847!*//*1390272498,178127433*/

if (self.CavalryLogger) { CavalryLogger.start_js(["INS5p"]); }

__d("BanzaiNectar",["Banzai"],function(a,b,c,d,e,f){var g=b('Banzai');function h(j){return {log:function(k,l,m){var n={e:l,a:m};g.post('nectar:'+k,n,j);}};}var i=h();i.create=h;e.exports=i;});
__d("AsyncDOM",["CSS","DOM"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('DOM'),i={invoke:function(j,k){for(var l=0;l<j.length;++l){var m=j[l],n=m[0],o=m[1],p=m[2],q=m[3],r=(p&&k)||null;if(o)r=h.scry(r||document.documentElement,o)[0];switch(n){case 'eval':(new Function(q)).apply(r);break;case 'hide':g.hide(r);break;case 'show':g.show(r);break;case 'setContent':h.setContent(r,q);break;case 'appendContent':h.appendContent(r,q);break;case 'prependContent':h.prependContent(r,q);break;case 'insertAfter':h.insertAfter(r,q);break;case 'insertBefore':h.insertBefore(r,q);break;case 'remove':h.remove(r);break;case 'replace':h.replace(r,q);break;default:}}}};e.exports=i;});
__d("Live",["Arbiter","AsyncDOM","AsyncSignal","ChannelConstants","DataStore","DOM","ServerJS","createArrayFrom","emptyFunction"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('AsyncDOM'),i=b('AsyncSignal'),j=b('ChannelConstants'),k=b('DataStore'),l=b('DOM'),m=b('ServerJS'),n=b('createArrayFrom'),o=b('emptyFunction');function p(r,s){s=JSON.parse(JSON.stringify(s));new m().setRelativeTo(r).handle(s);}var q={logAll:false,startup:function(){q.startup=o;g.subscribe(j.getArbiterType('live'),q.handleMessage.bind(q));},lookupLiveNode:function(r,s){var t=l.scry(document.body,'.live_'+r+'_'+s);t.forEach(function(u){if(k.get(u,'seqnum')===undefined){var v=JSON.parse(u.getAttribute('data-live'));k.set(u,'seqnum',v.seq);}});return t;},handleMessage:function(r,s){var t=s.obj,u=t.fbid,v=t.assoc,w=this.lookupLiveNode(u,v);if(!w)return false;w.forEach(function(x){h.invoke(t.updates,x);if(t.js)p(x,t.js);});},log:function(){if(q.logAll){var r=n(arguments).join(':');new i('/common/scribe_endpoint.php',{c:'live_sequence',m:r}).send();}}};e.exports=q;});
__d("legacy:live-js",["Live"],function(a,b,c,d){a.Live=b('Live');},3);
__d("DimensionLogging",["BanzaiNectar","DOMDimensions"],function(a,b,c,d,e,f){var g=b('BanzaiNectar'),h=b('DOMDimensions'),i=h.getViewportDimensions();g.log('browser_dimension','homeload',{x:i.width,y:i.height,sw:window.screen.width,sh:window.screen.height,aw:window.screen.availWidth,ah:window.screen.availHeight,at:window.screen.availTop,al:window.screen.availLeft});});
__d("AutosetTimezone",["AsyncRequest","emptyFunction"],function(a,b,c,d,e,f){var g=b('AsyncRequest'),h=b('emptyFunction'),i=false;function j(m){var n=new Date(),o=n.getTimezoneOffset()/30,p=n.getTime()/1000,q=Math.round((m-p)/1800),r=Math.round(o+q)%48;if(r==0){return 0;}else if(r>24){r-=Math.ceil(r/48)*48;}else if(r<-28)r+=Math.ceil(r/-48)*48;return r*30;}function k(m,n,o){if(!m||undefined==n)return;if(i)return;i=true;var p=-j(m);if(o||p!=n){var q='/ajax/timezone/update.php';new g().setURI(q).setData({gmt_off:p,is_forced:o}).setErrorHandler(h).setTransportErrorHandler(h).setOption('suppressErrorAlerts',true).send();}}var l={calculateTimezone:j,setTimezone:k};e.exports=l;});
__d("legacy:autoset-timezone",["AutosetTimezone"],function(a,b,c,d){var e=b('AutosetTimezone');a.AutosetTimezone=e;a.tz_calculate=e.calculateTimezone;a.tz_autoset=e.setTimezone;},3);